var searchData=
[
  ['x_0',['x',['../C:/Users/saket/OneDrive/Desktop/ePathshala/epathshala-Web/node_modules/uri-js/README.md#autotoc_md13937',1,'Breaking changes from 1.x'],['../C:/Users/saket/OneDrive/Desktop/ePathshala/epathshala-Web/node_modules/uri-js/README.md#autotoc_md13936',1,'Breaking changes from 2.x'],['../C:/Users/saket/OneDrive/Desktop/ePathshala/epathshala-Web/node_modules/uri-js/README.md#autotoc_md13935',1,'Breaking changes from 3.x'],['../C:/Users/saket/OneDrive/Desktop/ePathshala/epathshala-Web/node_modules/espree/README.md#autotoc_md10901',1,'Differences from Espree 2.x'],['../C:/Users/saket/OneDrive/Desktop/ePathshala/epathshala-Web/node_modules/espree/README.md#autotoc_md10904',1,'Esprima 2.x'],['../C:/Users/saket/OneDrive/Desktop/ePathshala/epathshala-Web/node_modules/ignore/README.md#autotoc_md11534',1,'Upgrade 2.x -&gt; 3.x']]],
  ['x_203_20x_1',['Upgrade 2.x -&amp;gt; 3.x',['../C:/Users/saket/OneDrive/Desktop/ePathshala/epathshala-Web/node_modules/ignore/README.md#autotoc_md11534',1,'']]],
  ['x_20to_202_200_200_2',['Migration from 1.x to 2.0.0',['../C:/Users/saket/OneDrive/Desktop/ePathshala/epathshala-Web/node_modules/deepmerge/readme.md#autotoc_md10705',1,'']]],
  ['x_20y_20options_3',['&lt;span class=&quot;tt&quot;&gt;merge(x, y, [options])&lt;/span&gt;',['../C:/Users/saket/OneDrive/Desktop/ePathshala/epathshala-Web/node_modules/deepmerge/readme.md#autotoc_md10712',1,'']]],
  ['x64_20msvc_4',['`@rollup/rollup-win32-x64-msvc`',['../C:/Users/saket/OneDrive/Desktop/ePathshala/epathshala-Web/node_modules/@rollup/rollup-win32-x64-msvc/README.md#autotoc_md9784',1,'']]],
  ['xl_3a_201536px_5',['Extra Large (xl: 1536px+)',['../md__c_1_2_users_2saket_2_one_drive_2_desktop_2e_pathshala_2epathshala-_web_2_r_e_s_p_o_n_s_i_v_e___d_e_s_i_g_n___s_u_m_m_a_r_y.html#autotoc_md14521',1,'']]],
  ['xs_20fn_6',['concatMap(xs, fn)',['../md__c_1_2_users_2saket_2_one_drive_2_desktop_2e_pathshala_2epathshala-_web_2node__modules_2concat-map_2_r_e_a_d_m_e.html#autotoc_md10435',1,'']]],
  ['xs_3a_200_20599px_7',['xs: 0 599px',['../md__c_1_2_users_2saket_2_one_drive_2_desktop_2e_pathshala_2epathshala-_web_2_r_e_s_p_o_n_s_i_v_e___d_e_s_i_g_n___s_u_m_m_a_r_y.html#autotoc_md14517',1,'Mobile (xs: 0-599px)'],['../md__c_1_2_users_2saket_2_one_drive_2_desktop_2e_pathshala_2epathshala-_web_2_r_e_s_p_o_n_s_i_v_e27efb1051f925944329d023f5a2e0964.html#autotoc_md14586',1,'Mobile (xs: 0-599px)']]]
];
